
hide circle

hide empty members

skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false
skinparam noteBackgroundColor white

skinparam class {
    fontStyle bold
    fontSize 14
    attributeFontSize 14
    stereotypeFontSize 14
}
